### ISSUE TITLE
JavaScript Group Capstone

### ISSUE THREAD

**Issue by Emmanuelaaron** [Hamzaoutdoors/js_capstone#21]
We are 2 people on the team and this is the [link](https://github.com/Hamzaoutdoors/js_capstone/projects/1) to our project

**Comment by henatan99** [comment]
Hi @Hamzaoutdoors , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [x] There should be a circle with the user's avatar on each card. Kindly see the example below and make changes. 
![image](https://user-images.githubusercontent.com/64894927/132259950-5a484539-1ed8-4bec-827b-7afbb2971e63.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Hamzaoutdoors** [comment]
_done .. Thank you for your review @henatan99_

**Comment by henatan99** [comment]
Hi @Hamzaoutdoors  && @Emmanuelaaron , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
